# Training configuration for AudioLLM

# Data paths
data_path: "path/to/audio_instruction_examples.json"
audio_dir: "path/to/audio"

# Model configuration
llama_model_id: "meta-llama/Llama-3.2-3B-Instruct"
whisper_model_id: "openai/whisper-large-v3-turbo"
lora_rank: 32

# Training hyperparameters
batch_size: 4
learning_rate: 5.0e-5
weight_decay: 0.01
max_grad_norm: 1.0
num_epochs: 3
warmup_ratio: 0.1
train_split: 0.9

# Data processing parameters
max_audio_length: 30 # seconds
text_max_length: 512
num_workers: 4

# Misc
seed: 42

# Wandb
wandb_project: "audio-llm"
wandb_run_name: "audio-llm-run-1"
